export const firstParagraph = `I'm civil engineer and after some time of thinking and visiting some dreams of the past, I rediscovered myself and decide to stop to construct buildings and begin to construct software and web applications.`;

export const secondParagraph = `🎮I love to play games//n
🎬Watching some movies and series on my free time//n
✅Concluded Front-end module of web development//n
📚Studying Back-end module at Trybe`;

const currentYear = new Date ().getFullYear();
const myAge = currentYear - 1994;

export const myresume = `
My name is Romildo Silva, I'm ${myAge} years old, born in Brazil, in a small city called Garanhuns of the state of Pernambuco. I'm graduate in civil engineering, post-graduate in safety and project management. For a long time I worked in different environments, like industry and civil constructions. In 2022, I was thinking about my life, my future expectations and my goals, It was when I figured about technologies, I was a lover of technologies since I was a little boy and also the process of creating something that could make the difference, on that day, I decide to search about career of development and to study something that could take me closer to my goal. When I discovered the Trybe, a school of technology that gave me the opportunity to study, with a remote studies, live classes and a rich content and support, and pay only after of to be employed. From this moment and on, my life passed for a big transformation, I needed to almost stop working to study again, for one more time I was not in my comfort zone, I was back to the zero point. But the things changed very quickly, in three months, I was developing smalls web pages, forms and web applications using HTML, CSS and JavaScript, I had concluded the fundamentals module, and I was very happy. In December of 2022, I finished the Front-End module, and wow, I was using a lot of tools, developing web applications much more complex than in fundamentals, at this point all I can say is that I'm in love of programming  and anxious to have an opportunity to work in a place where I can develop myself, passing through challenges and not just working anymore, but doing what I really love.`